ltweb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

# Định nghĩa các URL cho ứng dụng

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('polls.urls')),
]

# Nếu ở chế độ DEBUG, thêm cấu hình cho tệp tĩnh
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Nếu ở chế độ DEBUG, thêm cấu hình cho tệp đa phương tiện
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views
from .views import forgot_pass_view, homepage_view, login_view, register_view, cart_view, logout_view, product_detail, listbooks_view, add_cart, update_from_cart, remove_from_cart

app_name = 'polls'

urlpatterns = [
    path('', homepage_view, name='homepage'),
    path('forgot-password/', forgot_pass_view, name='forgot_password'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('shopping-cart/', cart_view, name='cart'),
    path('logout/', logout_view, name='logout'),
    path('item/<slug:slug>', product_detail, name='product_detail'),
    path('category/<slug:category_slug>', views.category_list, name='category_list'),
    path('search/', views.search, name='search'),
    path('lisbooks/', listbooks_view, name='listbooks'),
    path('add_cart/<int:product_id>/<int:quantity>', add_cart, name='add_cart'),
    path('update_from_cart/<int:product_id>/<int:quantity>', update_from_cart, name='update_from_cart'),
    path('remove_from_cart/<int:cart_id>', remove_from_cart, name='remove_from_cart'),
    path('account/', views.account_view, name='account'),
    path('payment/', views.payment_view, name='payment_view'),
    path('payment_process/', views.payment, name='payment'),
    path('payment_return/', views.payment_return, name='payment_return'),
]

polls/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
from django.urls import reverse
from django.db.models import Sum
from django.contrib.auth import get_user_model

# Manager cho CustomUser model
class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, phone, password=None, **extra_fields):
        # Nếu không có email, raise ValueError
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    # Tạo một superuser
    def create_superuser(self, email, username, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, username, phone, password, **extra_fields)

# Model CustomUser kế thừa từ AbstractBaseUser và PermissionsMixin
class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100, unique=True)
    phone = models.CharField(max_length=15, default='N/A')
    email = models.EmailField(unique=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'phone']

    def __str__(self):
        return self.username

# Model cho giỏ hàng (Cart)
class Cart(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    product_id = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.user.username} - Product {self.product_id} - Quantity {self.quantity}"

# Model danh mục (Category)
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

# Model sản phẩm (Product)
class Product(models.Model):
    id = models.IntegerField(primary_key=True)
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    create_by = models.CharField(max_length=255, default='admin')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    intro = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    suplier = models.CharField(max_length=255)
    publisher = models.CharField(max_length=255, blank=True)
    release_date = models.DateField()
    language = models.CharField(max_length=255)
    weight = models.IntegerField()
    size = models.CharField(max_length=255)
    page = models.IntegerField()
    book_quality = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    price = models.IntegerField()
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('polls:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

# Model đơn đặt hàng (Order)
class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    phone_num = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    date_order = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_item_quantity(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

# Model chi tiết đơn đặt hàng (OrderItem)
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    price = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    # lấy tiền của mỗi sản phẩm
    @property
    def get_total(self):
        total = self.price * self

polls/forms.py
from django import forms
from django.contrib.auth.hashers import make_password
from .models import CustomUser
from django.contrib.auth.forms import AuthenticationForm

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['username', 'phone', 'email', 'password']

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.password = make_password(self.cleaned_data['password'])

        if commit:
            user.save()

        return user

class LoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={'autofocus': True}),
    )
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput,
    )

class PaymentForm(forms.Form):
    name = forms.CharField(max_length=255)
    phone_num = forms.CharField(max_length=255)
    address = forms.CharField(max_length=255)
    amount = forms.CharField(max_length=255)

polls/views.py
# Imports
import hashlib
import hmac
import json
import urllib
import urllib.parse
import urllib.request
import random
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
from django.db import transaction
from django.db.models import Q, F
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.decorators.cache import cache_page

from .forms import RegistrationForm, PaymentForm, LoginForm
from .models import Category, Product, CustomUser, Cart, Order, OrderItem, WebsiteStats
from .vnpay import vnpay

# View cho việc đăng ký người dùng
def register_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            if request.user.is_authenticated:
                logout(request)
            return JsonResponse({'result': "Thành công"})
    else:
        form = RegistrationForm()
    return render(request, 'polls/register_index.html', {'form': form})

# View cho việc quên mật khẩu
def forgot_pass_view(request):
    return render(request, 'polls/forgot_pass_index.html')

# Cache trang chủ trong vòng 15 phút
@cache_page(60 * 15)
def homepage_view(request):
    # Lấy và tăng số lượng lượt truy cập tổng
    total_visits = increment_total_visits()

    # Lấy sản phẩm nổi bật
    feature_products = Product.objects.all()[:4]

    return render(request, 'polls/homepage_index.html', {'feature_products': feature_products, 'total_visits': total_visits})

# Hàm tăng số lượng lượt truy cập tổng
def increment_total_visits():
    new_stats = WebsiteStats.objects.create(total_visits=1)
    total_visits = new_stats.total_visits if new_stats else 0
    return total_visits

# View cho việc đăng nhập người dùng
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            # Xác thực thành công
            user = form.get_user()
            login(request, user)
            return homepage_view(request)
        else:
            messages.error(request, 'Tên người dùng hoặc mật khẩu không hợp lệ')
    else:
        form = LoginForm()

    return render(request, 'polls/login_index.html', {'form': form})

# View cho giỏ hàng của người dùng
@login_required
def cart_view(request):
    user = request.user
    list_item = []
    cart = Cart.objects.filter(user=user)
    for c in cart:
        list_item.append(c.product_id)

    item = Product.objects.filter(
        id__in=list_item
    )
    return render(request, 'polls/shopping_cart_index.html', {'items': item, 'cart': cart})

# View cho việc liệt kê tất cả sách
def listbooks_view(request):
    products = Product.objects.all()
    return render(request, 'polls/list_book_index.html', {'products': products})

# View cho việc đăng xuất
@login_required
def logout_view(request):
    logout(request)
    return redirect('/')

# View cho việc hiển thị chi tiết của một sản phẩm
def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    related_products = Product.objects.filter(category=product.category)[:4]
    return render(request, 'polls/onlybooks.html', {'product': product, 'related_products': related_products})

# View cho việc liệt kê sản phẩm trong một danh mục cụ thể
def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'polls/list_book_index.html', {'category': category, 'products': products})

# View cho việc tìm kiếm sản phẩm
def search(request):
    search_product = request.GET.get('search')
    uppercase_product = str(search_product).upper()
    products = ''
    if search_product:
        products = Product.objects.filter(Q(title__icontains=uppercase_product) & Q(description__icontains=uppercase_product))
    else:
        products = ''
    if products:
        count = products.count()
    else:
        count = 0
    return render(request, 'polls/search_product.html', {'products': products, 'search_product': search_product, 'count': count})

# View cho việc thêm một sản phẩm vào giỏ hàng
@login_required
def add_cart(request, product_id, quantity):
    user = request.user
    cart = Cart.objects.filter(user=user, product_id=product_id)
    if request.POST.get('amount'):
        quantity = request.POST.get('amount')
        quantity = int(quantity)

    if cart.exists():
        existed_cart = Cart.objects.get(user=user, product_id=product_id)
        existed_cart.quantity += quantity
        existed_cart.save()
    else:
        new_cart = Cart.objects.create(user=user, product_id=product_id, quantity=1)
    return homepage_view(request)

# View cho việc cập nhật số lượng sản phẩm trong giỏ hàng
@login_required
def update_from_cart(request, product_id, quantity):
    user = request.user
    cart = Cart.objects.get(user=user, product_id=product_id)

    quantity = int(quantity)
    cart.quantity = quantity
    cart.save()
    return homepage_view(request)

# View cho việc xóa một sản phẩm khỏi giỏ hàng
@login_required
def remove_from_cart(request, cart_id):
    cart = get_object_or_404(Cart, pk=cart_id)
    if request.method == 'POST':
        cart.delete()
    return render(request, 'polls/shopping_cart_index.html')

# View cho tài khoản người dùng
@login_required
def account_view(request):
    user = request.user
    orders = Order.objects.filter(user=user, paid=True)
    items = OrderItem.objects.filter(order__in=orders)
    total_order = len(orders)
    return render(request, 'polls/account_index.html', {'total_order': total_order, 'orders': orders, 'items': items, 'user': user})

# Hàm để tạo OrderItem instances
def create_order_item(request, order_id):
    user = request.user

polls/templates/polls/login_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/login_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/homepage_style.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>Document</title>
</head>
<!--Đây là trang đăng nhập của website-->
<body class="login-html">
    <!--header-->
    <header>
         <i class='bx bx-menu' style='color:#12f7ff' id="bx-menu">
            <div class="menu" id="menu">
                <ul class="sub-menu">
                    <li><a href="{% url 'polls:homepage' %}">Trang chủ</a></li>
                    <li><a href="{% url 'polls:listbooks' %}">Tất cả sản phẩm</a></li>
                    <li><a href="#">Thể loại</a>
                        <i class='bx bx-chevron-down' id="the-loai-chevron-down"></i>
                        <ul class="the-loai" id="the-loai">
                            <li><a href="#">Văn học</a></li>
                            <ul class="Van-hoc">
                                <li><a href="{% url 'polls:category_list' category_slug='van-hoc-hien-dai' %}">Văn học hiện đại</a></li>
                                <li><a href="{% url 'polls:category_list' category_slug='van-hoc-nuoc-ngoai' %}">Văn học nước ngoài</a></li>
                                <li><a href="#">Tiểu thuyết</a></li>
                                <li><a href="#">Ngôn tình</a></li>
                                <li><a href="#">Truyện ngắn - Tản văn</a></li>
                                <li><a href="#">Khoa học viễn tưởng</a></li>
                                <li><a href="#">Trinh thám - Kinh dị</a></li>
                                <li><a href="#">Tâm linh - Tôn giáo</a></li>
                                <li><a href="#">Y học - Sức khỏe</a></li>
                            </ul>
                            <li><a href="#">Kinh tế</a></li>
                            <ul class="Kinh-te">
                                <li><a href="#">Marketing - Bán hàng</a></li>
                                <li><a href="#">Quản trị kinh doanh</a></li>
                                <li><a href="#">Phân tích thị trường</a></li>
                            </ul>
                            <li><a href="#">Truyện tranh</a></li>
                            <li><a href="#">Thiếu nhi</a></li>
                            <ul class="Thieu-nhi">
                                <li><a href="#">Kỹ năng sống cho trẻ</a></li>
                                <li><a href="#">Nuôi dạy con</a></li>
                                <li><a href="#">Vừa chơi vừa học</a></li>
                                <li><a href="#">Sách tô màu</a></li>
                            </ul>
                            <li><a href="#">Sách giáo khoa</a></li>
                            <ul class="SGK">
                                <li><a href="#">Sách giáo khoa</a></li>
                                <li><a href="#">Sách bài tập</a></li>
                                <li><a href="#">Sách tham khảo</a></li>
                                <li><a href="#">Sách luyện thi</a></li>
                            </ul>
                            <li><a href="#">Phân loại khác</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Tác giả</a></li>
                    <li><a href="#">Nhà xuất bản</a>
                        <i class='bx bx-chevron-down' id="NXB-chevron-down"></i>
                        <ul class="NXB" id="NXB">
                            <li><a href="#">Nhã Nam</a></li>
                            <li><a href="#">NXB Trẻ</a></li>
                            <li><a href="#">IPM</a></li>
                            <li><a href="#">AZ Book</a></li>
                        </ul>
                    </li>
                    <li><a href="#contact">Liên hệ</a></li>
                </ul>
            </div>
        </i>
        <img src="{% static 'polls/image/logo.svg' %}" alt="">
        <a href="#" class="logo">Ngôi nhà của Cú</a>
        <ul class="search">
            <form action="{% url 'polls:search' %}" method="get">
            <li>
                <input type="text" placeholder="Tìm kiếm" name="search">
                <button type="submit"><i class='bx bx-search-alt' style='color:#12f7ff'></i></button>
            </li>
            </form>
            {% if user.is_authenticated %}
            <li><a href="{% url 'polls:cart' %}"><i class='bx bx-shopping-bag' style='color:#12f7ff'></i></a></li>
            <li><a href="{% url 'polls:account'%}"><i class='bx bxs-user' style='color:#12f7ff'></i></a></li>
            {% else %}
            <li><a href="{% url 'polls:login' %}"><i class='bx bx-shopping-bag' style='color:#12f7ff'></i></a></li>
            <li><a href="{% url 'polls:login' %}"><i class='bx bxs-user' style='color:#12f7ff'></i></a></li>
            {% endif %}
        </ul>
        <ul class="navlist">
           <li><a href="/">Trang chủ</a></li>
            <li><a href="/#about">Giới thiệu</a></li>
            <li><a href="/#contact">Liên hệ</a></li>
            <li><a href="/login">Đăng nhập</a></li>
        </ul>
    </header>

    <!--Đây là đường dẫn mỗi trang-->
    <ul class="breadcrumb">
        <li><a href="{% url 'polls:homepage' %}">Trang chủ</a></li>
        <li>Đăng nhập</li>
    </ul>


    <!--Nội dung chính của trang đăng nhập-->
    <img src="{% static 'polls/image/logo.svg' %}" alt="" id="small-logo">
    <div class="login">
        {% if user.is_authenticated %}
        <p>You are already logged in as {{ user.username }}. <a href="{% url 'polls:logout' %}">Đăng xuất</a></p>
        {% else %}
        <form id="loginForm" action="" method="post">
            {% csrf_token %}
            <h1>ĐĂNG NHẬP TÀI KHOẢN</h1>
            {% if form.non_field_errors %}
            <div class="form-control">
                <div class="row">
                    <p class="error">{{ form.non_field_errors }}</p>
                </div>
            </div>
            {% endif %}
            <div class="form-control">
                <div class="row">
                    <p>Tên đăng nhập</p>
                    <input id="username" name="username" type="text" placeholder="Nhập tên đăng nhập">
                </div>
                <div class="row"><small></small></div>
            </div>
            <div class="form-control">
                <div class="row">
                    <p>Mật khẩu</p>
                    <input id="password" name="password" type="password" placeholder="Nhập mật khẩu">
                </div>
                <div class="row"><small></small></div>
            </div>
            <div class="forgot_pass_or_reg">
                <p><a href="{% url 'polls:forgot_password' %}">Quên mật khẩu?</a></p>
                <p>or</p>
                <p>Chưa có tài khoản? <a href="{% url 'polls:register' %}">Đăng kí</a></p>
            </div>
            <button type="submit" class="btn-submit-login">Đăng nhập</button>
            {% endif %}
        </form>
    </div>
    <footer id="contact">
        <h2>Liên hệ</h2>
        <ul>
            <li><i class='bx bxs-car' style='color:#1d002c'></i><b> Địa chỉ:</b> Khu phố 6, P.Linh Trung, Tp.Thủ Đức, Tp.Hồ Chí Minh</li>
            <li><i class='bx bxs-phone' style='color:#1d002c'></i><b> Số điện thoại:</b> 0912XXXXXX</li>
            <li><i class='bx bx-envelope' style='color:#1d002c'></i><b> Email:</b> 21521195@gm.uit.edu.vn</li>
        </ul>
        <ul class="social">
            <i class='bx bxl-facebook-square'></i>
            <i class='bx bxl-instagram'></i>
        </ul>
    </footer>
</body>
<script src="{% static 'polls/js/homepage_script.js' %}"></script>
</html>

polls/templates/polls/payment_return.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/homepage_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/pay_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/account_style.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<!--Đây là trang thanh toán sản phẩm-->
<body class="pay-html">
    <!--header-->
    <header>
        <i class='bx bx-menu' style='color:#12f7ff' id="bx-menu">
            <div class="menu" id="menu">
                <ul class="sub-menu">
                    <li><a href="{% url 'polls:homepage' %}">Trang chủ</a></li>
                    <li><a href="{% url 'polls:listbooks' %}">Tất cả sản phẩm</a></li>
                    <li><a href="#">Sách nổi bật</a></li>
                    <li><a href="#">Sách bán chạy</a></li>
                    <li><a href="#">Thể loại</a>
                        <i class='bx bx-chevron-down' id="the-loai-chevron-down"></i>
                        <ul class="the-loai" id="the-loai">
                            <li><a href="#">Văn học</a></li>
                            <ul class="Van-hoc">
                                <li><a href="{% url 'polls:category_list' category_slug='van-hoc-hien-dai' %}">Văn học hiện đại</a></li>
                                <li><a href="{% url 'polls:category_list' category_slug='van-hoc-nuoc-ngoai' %}">Văn học nước ngoài</a></li>
                                <li><a href="#">Tiểu thuyết</a></li>
                                <li><a href="#">Ngôn tình</a></li>
                                <li><a href="#">Truyện ngắn - Tản văn</a></li>
                                <li><a href="#">Khoa học viễn tưởng</a></li>
                                <li><a href="#">Trinh thám - Kinh dị</a></li>
                                <li><a href="#">Tâm linh - Tôn giáo</a></li>
                                <li><a href="#">Y học - Sức khỏe</a></li>
                            </ul>
                            <li><a href="#">Kinh tế</a></li>
                            <ul class="Kinh-te">
                                <li><a href="#">Marketing - Bán hàng</a></li>
                                <li><a href="#">Quản trị kinh doanh</a></li>
                                <li><a href="#">Phân tích thị trường</a></li>
                            </ul>
                            <li><a href="#">Truyện tranh</a></li>
                            <li><a href="#">Thiếu nhi</a></li>
                            <ul class="Thieu-nhi">
                                <li><a href="#">Kỹ năng sống cho trẻ</a></li>
                                <li><a href="#">Nuôi dạy con</a></li>
                                <li><a href="#">Vừa chơi vừa học</a></li>
                                <li><a href="#">Sách tô màu</a></li>
                            </ul>
                            <li><a href="#">Sách giáo khoa</a></li>
                            <ul class="SGK">
                                <li><a href="#">Sách giáo khoa</a></li>
                                <li><a href="#">Sách bài tập</a></li>
                                <li><a href="#">Sách tham khảo</a></li>
                                <li><a href="#">Sách luyện thi</a></li>
                            </ul>
                            <li><a href="#">Phân loại khác</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Tác giả</a></li>
                    <li><a href="#">Nhà xuất bản</a>
                        <i class='bx bx-chevron-down' id="NXB-chevron-down"></i>
                        <ul class="NXB" id="NXB">
                            <li><a href="#">Nhã Nam</a></li>
                            <li><a href="#">NXB Trẻ</a></li>
                            <li><a href="#">IPM</a></li>
                            <li><a href="#">AZ Book</a></li>
                        </ul>
                    </li>
                    <li><a href="#contact">Liên hệ</a></li>
                </ul>
            </div>
        </i>
        <img src="{% static 'polls/image/logo.svg' %}" alt="">
        <a href="{% url 'polls:homepage' %}" class="logo">Ngôi nhà của Cú</a>
        <ul class="search">
            <form action="{% url 'polls:search' %}" method="get">
            <li>
                <input type="text" placeholder="Tìm kiếm" name="search">
                <button type='submit'><i class='bx bx-search-alt' style='color:#12f7ff'></i></button>
            </li>
           </form>
            {% if user.is_authenticated %}
            <li><a href="{% url 'polls:cart' %}"><i class='bx bx-shopping-bag' style='color:#12f7ff'></i></a></li>
            <li><a href="{% url 'polls:account'%}"><i class='bx bxs-user' style='color:#12f7ff'></i></a></li>
            {% else %}
            <li><a href="{% url 'polls:login' %}"><i class='bx bx-shopping-bag' style='color:#12f7ff'></i></a></li>
            <li><a href="{% url 'polls:login' %}"><i class='bx bxs-user' style='color:#12f7ff'></i></a></li>
            {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <ul class="navlist">
            <li><a href="{% url 'polls:homepage' %}">Trang chủ</a></li>
            <li><a href="{% url 'polls:homepage' %}#about">Giới thiệu</a></li>
            <li><a href="{% url 'polls:homepage' %}#contact">Liên hệ</a></li>
            <li>Hi, {{ user.username }}</li>
            <li><a href="{% url 'polls:logout' %}">Đăng xuất</a></li>
        </ul>
        {% else %}
        <ul class="navlist">
            <li><a href="{% url 'polls:homepage' %}">Trang chủ</a></li>
            <li><a href="{% url 'polls:homepage' %}#about">Giới thiệu</a></li>
            <li><a href="{% url 'polls:homepage' %}#contact">Liên hệ</a></li>
            <li><a href="{% url 'polls:login' %}">Đăng nhập</a></li>
        </ul>
        {% endif %}
    </header>

    <!--Đường dẫn mỗi trang-->
    <ul class="breadcrumb">
        <li><a href="{% url 'polls:homepage' %}">Trang chủ</a></li>
        <li><a href="{% url 'polls:cart' %}">Giỏ hàng</a></li>
        <li>Thanh toán</li>
    </ul>

    <!--Nội dung thanh toán-->
    <img src="{% static 'polls/image/logo.svg' %}" alt="" id="small-logo">
    <div class="pay">
        <h1>{{result}}</h1>
    </div>

    <!--Thông tin liên hệ-->
    <footer id="contact">
        <h2>Liên hệ</h2>
        <ul>
            <li><i class='bx bxs-car' style='color:#1d002c'></i><b> Địa chỉ:</b> Khu phố 6, P.Linh Trung, Tp.Thủ Đức, Tp.Hồ Chí Minh</li>
            <li><i class='bx bxs-phone' style='color:#1d002c'></i><b> Số điện thoại:</b> 0912XXXXXX</li>
            <li><i class='bx bx-envelope' style='color:#1d002c'></i><b> Email:</b> 21521195@gm.uit.edu.vn</li>
        </ul>
        <ul class="social">
            <i class='bx bxl-facebook-square'></i>
            <i class='bx bxl-instagram'></i>
        </ul>
    </footer>
    <script src="homepage_script.js"></script>
</body>
</html>